## 넘파이(Numpy)를 사용하는 이유

### 1. 파이썬의 넘파이(Numpy)는
* 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 패키지이다.
* 수치 계산을 위해 효율적으로 구현된 기능을 제공한다.
* 대규모 다차원 배열 데이터를 빠르고 효율적으로 사용한다.

### 2. 넘파이(Numpy)의 장점
* 빠르다. : 원소가 많아질수록 파이썬의 리스트보다 배열의 연산이 빠르다. 
* 편리하다. : 배열을 다루는데 필요한 메소드들이 구현되어있다.
* 상용된다. : 여러가지 환경에서 사용이 용이하다.






In [ ]:
# 넘파이 라이브러리 호출하기
import numpy as np

## 넘파이(Numpy)의 핵심, 배열(array)

### 1. 넘파이(Numpy)의 핵심인 배열(array)은
* 넘파이(Numpy)패키지의 ndarray클래스이다.
* 여러개의 데이터를 담고 있는 컨테이너형 자료구조이다.
* 동일한 데이터타입의 원소를 갖는 다차원배열이다.

### 2. 배열와 리스트의 비교 
* 위치에 대한 정보(index)로 요소를 가져오는 인덱싱(indexing) 비교 ex) 0번행과 2번행 불러오기
* 여러개의 요소를 집계하여 하나의 값으로 결과를 내는 집계연산 비교 ex) 각 행별 총합 구하기
* 각 요소별로 연산을 적용하는 요소간(element-wise) 연산 비교 ex) 각 요소별 1000과의 차이 구하기

위의 3가지를 리스트와 배열로써 비교하면 리스트에서는 불가능하거나 for문으로 작성해야하는 번거로움이 발생하나 배열에서는 손쉽게 작성할 수 있다.


In [ ]:
py_list = [
           [1,2,3],
           [10,20,30],
           [100,200,300]
]
py_list

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [ ]:
np_array = np.array(py_list)
np_array

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [ ]:
# 0번행과 2번행 불러오기 - 리스트
# py_list[[0,2]] 불가능
[py_list[0],py_list[2]]

[[1, 2, 3], [100, 200, 300]]

In [ ]:
# 0번행과 2번행 불러오기 - 배열
np_array[[0,2]]

array([[  1,   2,   3],
       [100, 200, 300]])

In [ ]:
# 각 행별 총합 구하기 - 리스트
[sum(row_list) for row_list in py_list]

[6, 60, 600]

In [ ]:
# 각 행별 총합 구하기 - 배열
np_array.sum(axis=1)

array([  6,  60, 600])

In [ ]:
# 각 요소별 1000과의 차이 구하기 - 리스트
[[1000 - v for v in row_list] for row_list in py_list]

[[999, 998, 997], [990, 980, 970], [900, 800, 700]]

In [ ]:
# 각 요소별 1000과의 차이 구하기 - 배열
1000 - np_array

array([[999, 998, 997],
       [990, 980, 970],
       [900, 800, 700]])

## Numpy 배열의 구성요소 
### 1. Numpy배열(Array)는
* 원소(elements), 자료형(Data-type), 모양(shape)으로 구성되어있다.
* 고유한 구성요소 조합은 배열(array)를 결정한다.
* 정의된 배열에서 원소(elements)의 개수는 바꿀수 없다.




In [ ]:
# 원소, 자료형, 모양 확인
py_list = [[1,2,3],[10,20,30],[100,200,300]]
ary = np.array(py_list)

In [ ]:
print(f'원소의 개수(size) : {ary.size}')
print(f'자료형(dtype) : {ary.dtype}')
print(f'모양(shape) : {ary.shape}')

원소의 개수(size) : 9
자료형(dtype) : int64
모양(shape) : (3, 3)


### 2. 원소의 개수는 바꿀 수 없다.
* ndarray 클래스의 메소드에는 원소의 개수가 바뀌는 메소드가 없다.


In [ ]:
# 리스트에서 원소의 개수를 추가하면
py_list.append([1000,2000,3000])
py_list

[[1, 2, 3], [10, 20, 30], [100, 200, 300], [1000, 2000, 3000]]

In [ ]:
# 배열에서도 append 메소드를 사용한다면
ary.append([1000,2000,3000]) # 오류가 발생한다.

AttributeError: ignored

In [ ]:
# 배열에서 원소의 개수를 추가하려면
ary = np.append(ary, [[1000,2000,3000]], axis=0)
ary
# np에서 새로 정의후 저장해야한다.

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

## 배열의 자료형(Data Type)
### 1. 배열의 자료형(dtype ; data type)은
* 배열에 포함된 원소들의 자료형이다. 
* 하나의 배열은 하나의 자료형을 갖는다.
* 그러므로 배열의 모든원소값은 동일한 자료형을 갖는다.
* 매개변수와 속성명으로 dtype을 쓴다.

In [ ]:
# 배열 자료형(dtype) 확인하기
ary.dtype

dtype('int64')

### 2. 자동으로 설정되는 배열의 자료형
* 배열 생성시, 입력한 원소들의 자료형을 파악하여 자동으로 설정


In [ ]:
# 서로 다른 자료형을 원소로 갖는 리스트
py_list = [1, 1.2, False]
py_list

[1, 1.2, False]

In [ ]:
# 서로 다른 자료형을 원소는 배열을 정의하면
ary = np.array(py_list)
ary

array([1. , 1.2, 0. ])

In [ ]:
ary.dtype

dtype('float64')

### 3. ndarray.astype()을 활용한 형변환

In [ ]:
# 내장된 자료형을 Numpy에서도 객체로 제공
np.float is float

True

In [ ]:
# ary의 자료형 확인
ary = np.array([[10,20,30,40,50,60]])
ary.dtype

dtype('int64')

In [ ]:
# ary의 형변환
ary = ary.astype(np.float)
ary

array([[10., 20., 30., 40., 50., 60.]])

In [ ]:
ary.dtype

dtype('float64')

### 4. 정보를 손실하는 형변환(type-casting)
* 적은 정보를 가진 자료형으로 형변환 했을 경우


In [ ]:
ary = np.array([[10.,20.,30.,40.,50.,60.]])
ary.dtype

dtype('float64')

In [ ]:
ary = ary.astype(np.bool)
ary

array([[ True,  True,  True,  True,  True,  True]])

In [ ]:
ary.dtype

dtype('bool')

In [ ]:
# 민약 다시 float으로 형변환 한다면, 당연하겠지만 정보 손실이 발생한다.
ary = ary.astype(np.float)
ary

array([[1., 1., 1., 1., 1., 1.]])

In [ ]:
ary.dtype

dtype('float64')

### 5. Numpy만의 자료형 객체는 왜 필요할까?


In [ ]:
# 만약, 배열 내 원소들의 값이 0부터 255사이의 실수로만 존재한다면
ary = np.array([0.,1.,2.,3.,4.])
ary

array([0., 1., 2., 3., 4.])

In [ ]:
ary.dtype

dtype('float64')

In [ ]:
# 배열이 저장된 메모리의 크기(byte 단위)
ary.nbytes

40

In [ ]:
# ary의 자료형을 np.unit8로 바꾸어주면
ary = ary.astype(np.uint8)
ary

array([0, 1, 2, 3, 4], dtype=uint8)

In [ ]:
# 저장된 메모리를 크게 아낄 수 있다.
ary.nbytes

5

## 배열의 모양(shape)
### 1. 배열의 모양(shape)은
* 다차원으로 구성된 원소들의 배열구조를 나타낸다.
* 하나의 배열은 하나의 모양(shape)을 갖는다.
* 매개변수와 속성명으로 shape를 쓴다.
* 차원(dimension), 축(axis), 각 축에서 원소의 개수로 결정된다.


In [ ]:
# 배열의 모양확인하기
ary = np.array([10,20,30,40,50,60])
ary.shape

(6,)

In [ ]:
ary = np.array([
                [10,20,30],
                [40,50,60]
])
ary.shape

(2, 3)

### 2. 모양을 나타낸 튜플(m, n)에서
* 튜플의 원소의 개수는 차원(dimension)
* 튜플의 원소의 인덱스는 축(axis)
* 튜플의 원소의 값은 각 축에서의 원소의 개수를 나타낸다.

### 3. 배열의 모양의 조건
* 각 축을 구성하는 원소의 갯수가 같아야 한다.

## 배열의 차원(dimension)
### 1. 배열의 차원(dimension)은
* 원소의 위치를 나타내기 위해 필요한 축(axis)의 개수이다.
* ' [ ' 와 ' ] ' 으로 구분한다.
* 매개변수와 속성명으로 ndim을 쓴다.
* 배열의 구조에서는 '원소의 원소'와 같이 겹으로 구성된 배열의 깊이이다.


In [ ]:
# 차원 확인하기 ndim
print(f'shape : {np.array(0).shape} 에서')
np.array(0).ndim

shape : () 에서


0

In [ ]:
print(f'shape : {np.array([0]).shape} 에서')
np.array([0]).ndim

shape : (1,) 에서


1

In [ ]:
print(f'shape : {np.array([[0]]).shape} 에서')
np.array([[0]]).ndim

shape : (1, 1) 에서


2

In [ ]:
print(f'shape : {np.array([[[0]]]).shape} 에서')
np.array([[[0]]]).ndim

shape : (1, 1, 1) 에서


3

### 2. 1차원 배열(n,)
* (n,) 모양을 갖는 1차원 배열, 벡터(vector)



In [ ]:
array_1d = np.array([10,20,30,40,50])
array_1d

array([10, 20, 30, 40, 50])

### 3. 2차원 배열(m, n)
* (m, n) 모양을 갖는 2차원 뱌열, 행렬(Matrix)

In [ ]:
array_2d = np.array([
                     [10,20,30,40,50],
                     [20,30,40,50,60],
                     [30,40,50,60,70]
])
array_2d

array([[10, 20, 30, 40, 50],
       [20, 30, 40, 50, 60],
       [30, 40, 50, 60, 70]])

### 3차원 이상의 배열(..., d, m, n)
* (..., d, m, n)모양을 갖는 다차원 행렬(Multidimensional Matrix), 텐서(Tensor)

In [ ]:
array_nd = np.array([
                     [
                      [10,20,30,40,50],
                      [20,30,40,50,60],
                      [30,40,50,60,70]
                     ],
                     [
                      [10,20,30,40,50],
                      [20,30,40,50,60],
                      [30,40,50,60,70]
                     ]
])
array_nd

array([[[10, 20, 30, 40, 50],
        [20, 30, 40, 50, 60],
        [30, 40, 50, 60, 70]],

       [[10, 20, 30, 40, 50],
        [20, 30, 40, 50, 60],
        [30, 40, 50, 60, 70]]])

## 배열의 축(axis)
### 1. 배열의 축(axis)는 
* 원소의 위치를 나타낼때 필요한 기준이다.
* N차원 배열에서 0부터 N-1까지 N개의 축이 존재한다.
* 매개변수명로 axis을 쓴다.
* 배열의 구조에서는 깊이의 지표(index)를 의미한다.
* 배열에서 인덱싱과 연산의 방향을 나타낼때 사용한다.



### 2. 1차원 배열(벡터)에서의 축(axis)

In [ ]:
array_1d = np.array([10,20,30,40,50,60])
array_1d

array([10, 20, 30, 40, 50, 60])

In [ ]:
# (0번 축 원소의 개수 ,)만으로 구성
array_1d.shape

(6,)

In [ ]:
# 0번 축에서 1번째 값
array_1d[1] # 이 배열에서 원소의 위치를 나타낼 때 한개의 축에서의 위치면 된다.

20

In [ ]:
array_1d.sum(axis = 0)

210

In [ ]:
array_1d.sum(axis = 1) # array_1d는 axis가 0까지만 있기 때문에 불가능하다.

AxisError: ignored

In [ ]:
# 모양 튜플의 인덱스는 '축'과 동일한 의미를 가진다.
array_1d.shape[0]

6

### 3. 2차원 배열(행렬)에서의 축(axis)

In [ ]:
array_2d = np.array([
                     [10,20,30],
                     [40,50,60]
])
array_2d

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# 배열의 모양이 (0번 축 원소의 개수, 1번 축 원소의 개수)로 구성
array_2d.shape

(2, 3)

In [ ]:
# 0번 축에서 0번째, 1번 축에서 2번째 원소
array_2d[0,2]

30

In [ ]:
print(array_2d.sum(axis = 0))
print(array_2d[0, :] + array_2d[1, :])

[50 70 90]
[50 70 90]


In [ ]:
print(array_2d.sum(axis = 1))
print(array_2d[:, 0] + array_2d[:, 1] + array_2d[:, 2])

[ 60 150]
[ 60 150]


In [ ]:
# 모양 튜플의 인덱스는 '몇번째 축'과 동일한 의미를 가진다.
array_2d.shape[0] # 인덱스 0 : 0번재 축의 원소의 개수

2

In [ ]:
array_2d.shape[1] # 인덱스 1 : 1번째 축의 원소의 개수

3

### 4. 3차원 배열(텐서)에서의 축(axis)

In [ ]:
array_nd = np.array([
                     [
                      [10,20,30],
                      [40,50,60]
                     ],
                     [
                      [15,25,35],
                      [45,55,65]
                     ]
])
array_nd

array([[[10, 20, 30],
        [40, 50, 60]],

       [[15, 25, 35],
        [45, 55, 65]]])

In [ ]:
# 배열의 모양이 (0번 축 원소의 개수, 1번 축 원소의 개수, 2번 축 원소의 개수,...)으로 구성
array_nd.shape

(2, 2, 3)

In [ ]:
# 0번 축에서 1번째, 1번 축에서 0번째 원소, 2번 축에서 2번째 원소
array_nd[1,0,2] # 한 원소의 위치는 세 축에서 원소의 위치로 표현된다.

35

In [ ]:
display(array_nd.sum(axis=0))
array_nd[0, :, :] + array_nd[1, :, :]

array([[ 25,  45,  65],
       [ 85, 105, 125]])

array([[ 25,  45,  65],
       [ 85, 105, 125]])

In [ ]:
display(array_nd.sum(axis=1))
array_nd[:, 0, :] + array_nd[:, 1, :]

array([[ 50,  70,  90],
       [ 60,  80, 100]])

array([[ 50,  70,  90],
       [ 60,  80, 100]])

In [ ]:
display(array_nd.sum(axis=2))
array_nd[:, :, 0] + array_nd[:, :, 1] + array_nd[:, :, 2]

array([[ 60, 150],
       [ 75, 165]])

array([[ 60, 150],
       [ 75, 165]])

In [ ]:
# 모양 튜플의 인덱스는 '몇번째 축'과 동일한 의미를 가진다.
array_nd.shape[0] # 인덱스 0: 0번째 축의 원소의 개수

2

In [ ]:
array_nd.shape[1] # 인덱스 1: 1번째 축의 원소의 개수

2

In [ ]:
array_nd.shape[2] # 인덱스 2: 2번째 축의 원소의 개수

3

## 배열 생성하기 
### 1. 배열 생성하기 - 다른 자료로부터 생성
* 다른 자료구조를 변환하는 np.array()


In [ ]:
ary = np.array((1,2,3,4,5))
ary

array([1, 2, 3, 4, 5])

* 기존의 배열을 복사하는 np.copy()

In [ ]:
ary_2 = np.copy(ary)
ary_2

array([1, 2, 3, 4, 5])

* ary_3 = ary를 한다면?

In [ ]:
ary_3 = ary

array([1, 2, 3, 4, 5])

In [ ]:
print(id(ary))
print(id(ary_3))

139642648275904
139642648275904


In [ ]:
# 같은 위치를 가리킬때 원소값을 바꾼다면
ary[0] = 6
ary

array([6, 2, 3, 4, 5])

In [ ]:
# 두 변수가 모두 바뀐다.
ary_3

array([6, 2, 3, 4, 5])

In [ ]:
# copy를 이용하면
ary_4 = np.copy(ary)
ary_4

array([6, 2, 3, 4, 5])

In [ ]:
print(id(ary_4))
print(id(ary))

139642648327552
139642648275904


In [ ]:
ary[0] = 1
ary

array([1, 2, 3, 4, 5])

In [ ]:
ary_4 # 서로 다른 값을 가진다.

array([6, 2, 3, 4, 5])

### 2. 배열 생성하기 - 구성요소를 결정하여 생성
* 배열은 원소(elements), 자료형(Data-type), 모양(shape)에 의해 결정된다.

### 3. 원소의 값이 일전한 배열 생성하기
* np.zeros(), np.ones(), np.full()

In [ ]:
# 원소의 값이 모두 0이며, 3행 2열로 구성된 float64 배열
np.zeros(shape=(3,2), dtype = np.float64)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# 원소의 값이 모두 1이며, 3행 2열로 구성된 float64 배열
np.ones(shape=(3,2), dtype = np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 원소의 값이 모두 3이며, 3행 2열로 구성된 float64 배열
np.full(shape=(3,2), fill_value=3., dtype = np.float64)

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

### 4. 기존의 배열과 동일한 모양의 배열 생성하기
* np.zeros_like(), np.ones_like(), np.full_like()

In [ ]:
#  모양을 본 딴 배열(2,3) 모양의 배열, ary
ary = np.array([
                [1,2,3],
                [4,5,6]
])
print(ary)
print(ary.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# ary와 같은 모양을 가지면서 모든 요소의 값이 0인 배열
np.zeros_like(ary, dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# ary와 같은 모양을 가지면서 모든 요소의 값이 1인 배열
np.ones_like(ary, dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# ary와 같은 모양을 가지면서 모든 요소의 값이 3인 배열
np.full_like(ary, fill_value=3, dtype=np.int)

array([[3, 3, 3],
       [3, 3, 3]])

### 5. 같은 간격의 값으로 구성된 등간격배열 생성하기
* 간격의 크기를 지정하여 등간격 배열을 만드는 np.arange()

In [ ]:
# 원소간 1의 간격을 가지고 0부터 20까지의 값을 갖는 등간격배열 만들기
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 원소간 2의 간격을 가지고 0부터 20까지의 값을 갖는 등간격배열 만들기
np.arange(0,20,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

* 원소의 개수를 지정하여 등간격배열을 만드는 np.linspace()

In [ ]:
# 0부터 20까지의 값을 갖는 50개 원소의 등간격배열 만들기
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [ ]:
# 0부터 20까지의 값을 갖는 10개 원소의 등간격배열 만들기
np.linspace(0,20,num=10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])